# Generated by Django 4.1.5 on 2023-01-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
