# Generated by Django 4.1.5 on 2023-01-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('placed_on', models.DateTimeField()),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
