# Generated by Django 4.1.5 on 2023-01-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0003_alter_order_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
