# Generated by Django 4.1.5 on 2023-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0004_verf_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='verf_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_otp', models.IntegerField()),
            ],
        ),
    ]
