# Generated by Django 4.1.3 on 2023-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0007_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_signature',
        ),
    ]
