# Generated by Django 4.1.3 on 2023-01-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0008_payment_remove_order_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='razor_payment',
        ),
    ]
