# Generated by Django 4.1.3 on 2023-01-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0009_rename_payment_razor_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='razor_payment',
            new_name='orderpayment',
        ),
    ]
