# Generated by Django 4.1.3 on 2023-01-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0010_rename_razor_payment_orderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='uid',
        ),
    ]
